services:
#    flower_core.example:
#        class: Flower\CoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    form.type.event:
        class: Flower\PlannerBundle\Form\Type\EventType
        arguments: ["@security.context"]
        tags:
            - { name: form.type, alias: event_type }   