services:
#    flower_core.example:
#        class: Flower\CoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    form.type.event:
        class: Flower\PlannerBundle\Form\Type\EventType
        arguments: ["@security.context"]
        tags:
            - { name: form.type, alias: event_type }

    form.type.event_quick:
            class: Flower\PlannerBundle\Form\Type\EventQuickType
            arguments: ["@security.context"]
            tags:
                - { name: form.type, alias: event_type }

    flower.core.service.reminder:
        class: Flower\PlannerBundle\Service\ReminderService
        calls:
          - [ setContainer,[ @service_container ]]