<?php

namespace Flower\PlannerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventStatusRepository extends EntityRepository
{

}