<?php

namespace Flower\PlannerBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Flower\ModelBundle\Entity\Planner\EventStatus;

/**
 * EventStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventStatusRepository extends EntityRepository
{

}