<?php

namespace Flower\PlannerBundle\Repository;

use Doctrine\ORM\EntityRepository;
use DateTime ;
/**
 * ReminderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReminderRepository extends EntityRepository
{
	public function getAllPendingReminders(DateTime $dateFrom){
		$qb = $this->createQueryBuilder("re");
		$qb->where("re.date <= :dateFrom");
		$qb->andWhere("re.date > re.updated");
		$qb->setParameter("dateFrom", $dateFrom);
		return $qb->getQuery()->getResult();
	}
	public function countAllPendingReminders(DateTime $dateFrom){
		$qb = $this->createQueryBuilder("re");
		$qb->select('COUNT(re)');
		$qb->where("re.date <= :dateFrom");
		$qb->andWhere("re.date > re.updated");
		$qb->setParameter("dateFrom", $dateFrom);
		$query = $qb->getQuery();
		return $query->getSingleScalarResult();
	}
		public function queryOwnedBy($user) {

			$query = $this->createQueryBuilder('r')
				->where('r.user = :id')                
				->setParameter('id', $user->getId());
			return $query;
		}

		public function findOwnedBy($user) {
			return $this->queryOwnedBy($user)
					->getQuery()
					->getResult();
		}
}